name: pharmacy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_icons: 1.1.0
  cupertino_icons: ^0.1.2
  feather_icons_flutter: ">=4.7.4"
  font_awesome_flutter: '>= 4.7.0'

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo_Paaji/BalooPaaji2-Regular.ttf
        - asset: assets/fonts/Baloo_Paaji/BalooPaaji2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Baloo_Paaji/BalooPaaji2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Baloo_Paaji/BalooPaaji2-Medium.ttf
          weight: 500
    
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/quicksand/Quicksand-Light.ttf
          weight: 400
        - asset: assets/fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
          weight: 600
          
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
